#!/usr/bin/env bash
# Frolo installer for Debian/Ubuntu (amd64 + arm64). Safe to rerun.
#
#   sudo ./install.sh                  # install (or update in place)
#   sudo ./install.sh update           # pull the pinned release + restart
#   sudo ./install.sh uninstall        # remove Frolo, KEEP data
#   sudo ./install.sh uninstall --remove-data   # ALSO delete persistent data
#   sudo ./install.sh backup [file]    # back up the data volume to a tarball
#   sudo ./install.sh restore <file>   # restore the data volume from a tarball
#   ./install.sh diagnostics           # print environment + health info
#
# Frolo runs as a Docker container on port 4512 (LAN only). It NEVER opens a
# router mapping to expose itself. No development or production signing keys are
# downloaded or generated by this script.

set -euo pipefail

FROLO_VERSION="0.1.0-beta.1"
FROLO_IMAGE="${FROLO_IMAGE:-ghcr.io/meowerity/frolo:${FROLO_VERSION}}"
FROLO_DIR="/opt/frolo"
DATA_DIR="${FROLO_DIR}/data"
COMPOSE_FILE="${FROLO_DIR}/docker-compose.yml"
DATA_VOLUME="frolo-data"

log()  { printf "\033[0;36m[frolo]\033[0m %s\n" "$*"; }
warn() { printf "\033[0;33m[frolo]\033[0m %s\n" "$*" >&2; }
err()  { printf "\033[0;31m[frolo]\033[0m %s\n" "$*" >&2; }
die()  { err "$*"; exit 1; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    die "Please run as root (use sudo)."
  fi
}

detect_arch() {
  local m; m="$(uname -m)"
  case "$m" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    *) die "Unsupported architecture: $m (Frolo supports amd64 and arm64)." ;;
  esac
}

check_os() {
  if [ ! -f /etc/os-release ]; then
    die "Cannot detect OS. Frolo's installer supports Debian and Ubuntu."
  fi
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}" in
    debian|ubuntu) log "Detected ${PRETTY_NAME:-$ID}." ;;
    *) warn "This installer targets Debian/Ubuntu. Detected '${ID:-unknown}'. Continuing best-effort." ;;
  esac
}

check_resources() {
  local mem_kb; mem_kb="$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
  if [ "$mem_kb" -gt 0 ] && [ "$mem_kb" -lt 500000 ]; then
    warn "Low memory detected (<512MB). Frolo should run but may be slow."
  fi
}

ensure_docker() {
  if command -v docker >/dev/null 2>&1; then
    log "Docker found: $(docker --version)"
  else
    log "Docker not found. Installing Docker Engine via the official convenience script…"
    curl -fsSL https://get.docker.com | sh
  fi
  if ! docker compose version >/dev/null 2>&1; then
    die "Docker Compose v2 is required (docker compose). Please install it and rerun."
  fi
  if ! docker info >/dev/null 2>&1; then
    die "Docker daemon is not running. Start it and rerun."
  fi
}

write_compose() {
  mkdir -p "$FROLO_DIR" "$DATA_DIR"
  chmod 700 "$DATA_DIR"
  # Generate a local, per-install secret file (0600) if missing. This is a local
  # runtime secret only — NOT a signing key.
  if [ ! -f "${FROLO_DIR}/.env" ]; then
    umask 077
    {
      echo "FROLO_IMAGE=${FROLO_IMAGE}"
      echo "FROLO_BIND=0.0.0.0"
      echo "FROLO_BEHIND_TLS=0"
    } > "${FROLO_DIR}/.env"
    chmod 600 "${FROLO_DIR}/.env"
  fi
  cat > "$COMPOSE_FILE" <<YAML
services:
  frolo:
    image: \${FROLO_IMAGE:-${FROLO_IMAGE}}
    container_name: frolo
    restart: unless-stopped
    ports:
      - "\${FROLO_BIND:-0.0.0.0}:4512:4512"
    environment:
      FROLO_PORT: "4512"
      FROLO_HOST: "0.0.0.0"
      FROLO_DATA_DIR: "/opt/frolo/data"
      FROLO_WEB_ROOT: "/app/web"
      FROLO_BEHIND_TLS: "\${FROLO_BEHIND_TLS:-0}"
    volumes:
      - ${DATA_VOLUME}:/opt/frolo/data
    stop_grace_period: 20s
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:4512/api/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
volumes:
  ${DATA_VOLUME}:
    name: ${DATA_VOLUME}
YAML
  log "Wrote ${COMPOSE_FILE}"
}

compose() { docker compose --env-file "${FROLO_DIR}/.env" -f "$COMPOSE_FILE" "$@"; }

detect_ip() {
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [ -n "$ip" ] || ip="localhost"
  echo "$ip"
}

wait_healthy() {
  log "Waiting for Frolo to become healthy…"
  local tries=0
  until curl -fsS "http://127.0.0.1:4512/api/health" >/dev/null 2>&1; do
    tries=$((tries + 1))
    if [ "$tries" -gt 60 ]; then
      err "Frolo did not become healthy in time. Check logs: docker logs frolo"
      return 1
    fi
    sleep 2
  done
}

cmd_install() {
  require_root
  check_os
  local arch; arch="$(detect_arch)"
  log "Installing Frolo ${FROLO_VERSION} (${arch})"
  check_resources
  ensure_docker
  write_compose
  log "Pulling pinned image ${FROLO_IMAGE}…"
  compose pull || warn "Could not pull image (offline or not published yet). If you built locally, set FROLO_IMAGE to your local tag."
  compose up -d
  if wait_healthy; then
    local ip; ip="$(detect_ip)"
    printf "\n\033[0;32mFrolo is ready at http://%s:4512\033[0m\n\n" "$ip"
    log "LAN access only. For remote use, put Frolo behind an HTTPS reverse proxy."
  fi
}

cmd_update() {
  require_root
  ensure_docker
  [ -f "$COMPOSE_FILE" ] || die "Frolo is not installed (no ${COMPOSE_FILE})."
  log "Updating to ${FROLO_IMAGE}…"
  compose pull
  compose up -d
  wait_healthy && log "Update complete."
}

cmd_uninstall() {
  require_root
  [ -f "$COMPOSE_FILE" ] || { warn "Frolo does not appear to be installed."; return 0; }
  log "Stopping Frolo…"
  compose down || true
  if [ "${1:-}" = "--remove-data" ]; then
    warn "Removing persistent data volume '${DATA_VOLUME}' and ${FROLO_DIR} (explicitly requested)."
    docker volume rm "${DATA_VOLUME}" 2>/dev/null || true
    rm -rf "${FROLO_DIR}"
    log "Frolo and its data have been removed."
  else
    log "Frolo stopped and removed. Your data volume '${DATA_VOLUME}' is PRESERVED."
    log "To also delete data, rerun: $0 uninstall --remove-data"
  fi
}

cmd_backup() {
  require_root
  local out="${1:-frolo-backup-$(date +%Y%m%d-%H%M%S).tar.gz}"
  log "Backing up data volume '${DATA_VOLUME}' to ${out}…"
  docker run --rm -v "${DATA_VOLUME}:/data:ro" -v "$(pwd):/backup" busybox \
    tar czf "/backup/${out}" -C /data .
  log "Backup written to ${out}"
}

cmd_restore() {
  require_root
  local file="${1:-}"
  [ -n "$file" ] && [ -f "$file" ] || die "Usage: $0 restore <backup.tar.gz>"
  warn "Restoring will OVERWRITE the current data volume '${DATA_VOLUME}'."
  compose down 2>/dev/null || true
  docker volume create "${DATA_VOLUME}" >/dev/null
  docker run --rm -v "${DATA_VOLUME}:/data" -v "$(pwd):/backup" busybox \
    sh -c "rm -rf /data/* && tar xzf /backup/$(basename "$file") -C /data"
  compose up -d
  wait_healthy && log "Restore complete."
}

cmd_diagnostics() {
  echo "── Frolo diagnostics ──"
  echo "version (installer): ${FROLO_VERSION}"
  echo "image:               ${FROLO_IMAGE}"
  echo "arch:                $(uname -m)"
  if [ -f /etc/os-release ]; then . /etc/os-release; echo "os:                  ${PRETTY_NAME:-unknown}"; fi
  echo -n "docker:              "; command -v docker >/dev/null 2>&1 && docker --version || echo "not installed"
  echo -n "compose:             "; docker compose version 2>/dev/null || echo "not installed"
  echo -n "container:           "; docker ps --filter name=frolo --format '{{.Status}}' 2>/dev/null || echo "n/a"
  echo -n "health:              "; curl -fsS http://127.0.0.1:4512/api/health 2>/dev/null || echo "unreachable"
  echo
  echo "data dir:            ${DATA_DIR}"
  echo "volume:              ${DATA_VOLUME}"
}

usage() {
  cat <<EOF
Frolo installer (${FROLO_VERSION})

Usage: $0 [command]

  (no command)            Install or update Frolo in place
  update                  Pull the pinned release and restart
  uninstall               Remove Frolo, keep data
  uninstall --remove-data Remove Frolo AND delete persistent data
  backup [file]           Back up the data volume to a tarball
  restore <file>          Restore the data volume from a tarball
  diagnostics             Print environment + health info
EOF
}

main() {
  local cmd="${1:-install}"
  case "$cmd" in
    install) cmd_install ;;
    update) cmd_update ;;
    uninstall) shift || true; cmd_uninstall "${1:-}" ;;
    backup) shift || true; cmd_backup "${1:-}" ;;
    restore) shift || true; cmd_restore "${1:-}" ;;
    diagnostics|diag) cmd_diagnostics ;;
    -h|--help|help) usage ;;
    *) usage; exit 1 ;;
  esac
}

main "$@"
